[package]
name = "fix_gtdb_mg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.18"
flate2 = "1.0.33"
#phylotree = "0.1.2"
phylotree = { git = "https://github.com/4less/phylotree-rs" }
thiserror = "1.0.64"
